Define layout
equinix-labs/terraform-equinix-kubernetes-addons pull request #3
Opened 2022-12-12 17:49 UTC by ocobleseqx

2022-12-14 02:09 UTC, displague commented on variables.tf
> +    description = "Depending on your setup, you may need to specify the path to the kubeconfig file hosted on the remote server"
`private_key` and `kubeconfig_remote_path` seam reasonable to start with. very practical.

I believe @ctreatma was suggesting we recommend implicit provider configuration eventually, if we can overcome some obstacles: https://github.com/equinix-labs/terraform-equinix-kubernetes-addons/pull/2#issuecomment-1344550066

In that ever becomes the case, perhaps the user would be able to do something like this:

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins
```hcl
provider "kubernetes" {
  // seems provider config values can't come from a derived Terraform resource property?
  // Nest modules as a workaround to use a Metal Device or EIP address here?
  host                   = var.cluster_endpoint  
  cluster_ca_certificate = base64decode(var.cluster_ca_cert)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "ssh" // I only assume this will work :shrug:
    args        = ["-i", var.ssh_key, "cat /etc/kubernetes/admin.conf"]
  }
}
```


Another approach we may want to recommend in the future - is to prepare your own Kubernetes keys in advance and define your endpoint IPs in advance (assigned server IPs from EIP). @cprivitere has some k8s projects that take this approach.

2022-12-14 02:16 UTC, displague commented on examples/simple/variables.tf
> +variable project {
nit: terraform fmt

2022-12-14 02:16 UTC, displague commented on modules/metallb/outputs.tf
> +  value = local.ip_address_pools
nit: description

2022-12-14 19:45 UTC, ctreatma submitted a review, later dismissed
🚀

2022-12-14 21:15 UTC, cprivitere commented
This worked here for me, but it requires kubectl be installed in a default path location that /bin/sh will check. Mine was not as I use the kubectl from brew, so I had to do some setup before it would work.

2022-12-14 21:15 UTC, cprivitere commented
/approve

2022-12-14 21:15 UTC, cprivitere approved these changes

2022-12-14 21:18 UTC, cprivitere commented
Other notes: Had to add the following to examples/simple/main.tf to make it work:

Inside the module definition:

```hcl
  ssh_user        = var.user
```
Then below the module definition

```hcl
terraform {
  required_providers {
    equinix = {
      source = "equinix/equinix"
    }
  }
}

provider "equinix" {
  auth_token = var.auth_token
}
```

And of course that means I had to add user and auth_token variables to variables.tf

2022-12-14 21:28 UTC, cprivitere requested changes
I think I remember us not wanting to add the provider block, so here's some suggested code just for the user variable.

2022-12-14 21:28 UTC, cprivitere commented on modules/metallb/examples/simple/main.tf
> +  ssh_host        = var.host
```suggestion
  ssh_host        = var.host
  ssh_user        = var.user
```

2022-12-14 21:28 UTC, cprivitere commented on modules/metallb/examples/simple/variables.tf
> +
```suggestion

variable "user" {
  type        = string
  description = "The username of the ssh key used to connect to the server defined in host"
}

```

2022-12-15 13:55 UTC, displague commented on variables.tf
> +    description = "Depending on your setup, you may need to specify the path to the kubeconfig file hosted on the remote server"
https://medium.com/@danieljimgarcia/dont-use-the-terraform-kubernetes-manifest-resource-6c7ff4fe629a calls out two benefits of the `kubectl` provider over the `kubernetes` provider that are applicable here:
- kubernetes provider requires CRDs are already present, kubectl doesn't
- kubernetes provider requires K8s API is present at initialization, kubectl doesn't

The post has some other points that are worth checking out.

2022-12-15 13:59 UTC, displague commented on variables.tf
> +    description = "Depending on your setup, you may need to specify the path to the kubeconfig file hosted on the remote server"
@cprivitere's comment:

> it requires kubectl be installed in a default path

We'll have to call this out in the root README.md or perhaps in the README.md of each submodule that depends on kubectl.  The root could give blanket advise that some modules require kubectl (or local helm tools, if that is the case). We could try to local-exec a prerequisite check if we want to do more.

2022-12-15 15:17 UTC, ocobleseqx commented
> I think I remember us not wanting to add the provider block, so here's some suggested code just for the user variable.

Thanks @cprivitere, It's a good practice to have both provider and terraform blocks in the examples, I forgot to declare them, and it's interesting that I didn't get an error, perhaps because I use credentials with the environment variables? but I didn't know that it could work without including the provider. I will update the example

2022-12-15 19:51 UTC, ctreatma approved these changes

2022-12-15 20:27 UTC, cprivitere commented
Something I noticed today is that it always errors out on the first apply. You have to wait for the pods to be up and ready before you will get a successful apply.  Before that you get this:

```
module.terraform-equinix-kubernetes-addons.module.metallb[0].null_resource.config_metallb (remote-exec): Error from server (InternalError): error when creating "/tmp/metallb-config.yaml": Internal error occurred: failed calling webhook "bgppeersvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta2-bgppeer?timeout=10s": dial tcp 10.98.239.66:443: connect: connection refused
module.terraform-equinix-kubernetes-addons.module.metallb[0].null_resource.config_metallb (remote-exec): Error from server (InternalError): error when creating "/tmp/metallb-config.yaml": Internal error occurred: failed calling webhook "bgppeersvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta2-bgppeer?timeout=10s": dial tcp 10.98.239.66:443: connect: connection refused
module.terraform-equinix-kubernetes-addons.module.metallb[0].null_resource.config_metallb (remote-exec): Error from server (InternalError): error when creating "/tmp/metallb-config.yaml": Internal error occurred: failed calling webhook "bgpadvertisementvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-bgpadvertisement?timeout=10s": dial tcp 10.98.239.66:443: connect: connection refused
module.terraform-equinix-kubernetes-addons.module.metallb[0].null_resource.config_metallb (remote-exec): Error from server (InternalError): error when creating "/tmp/metallb-config.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": dial tcp 10.98.239.66:443: connect: connection refused
module.terraform-equinix-kubernetes-addons.module.metallb[0].null_resource.config_metallb (remote-exec): Error from server (InternalError): error when creating "/tmp/metallb-config.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": dial tcp 10.98.239.66:443: connect: connection refused
╷
│ Error: remote-exec provisioner error
│ 
│   with module.terraform-equinix-kubernetes-addons.module.metallb[0].null_resource.config_metallb,
│   on ../../../../modules/metallb/main.tf line 88, in resource "null_resource" "config_metallb":
│   88:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1049893966.sh": Process exited with status 1
```

2022-12-15 20:28 UTC, cprivitere approved these changes

2022-12-15 21:00 UTC, merged